spring.application.name=DomRitaExercise
spring.datasource.url=jdbc:postgresql://localhost:5432/domrita_exercise
spring.datasource.username=postgres
spring.datasource.password=598916
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true